# vim: set ft=yaml ts=2 expandtab:
---

dependency:
  name: galaxy

driver:

  name: docker


lint: |
  set -e
  ! grep -r "no_log: false" .
  yamllint .
  ansible-lint -v
  flake8 -v

platforms:
- name: ci-centos8
  image: centos:8
  command: /lib/systemd/systemd
  volumes:
  - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  tmpfs:
  - /tmp
  - /run
  - /run/lock
  capabilities:
  - SYS_ADMIN
  privileged: ${CI_CONTAINER_PRIVILEGED:-false}
  pre_build_image: ${CI_CONTAINER_PREBUILT:-false}
  tty: true

provisioner:
  name: ansible
  ansible_args:
    - --tags=all,debug
    - --diff
  config_options:
    defaults:
      gathering: smart
      interpreter_python: auto
  lint:
    name: ansible-lint

verifier:
  name: ansible
  lint:
    name: ansible-lint

...
